services:

    pdir.klaro.configlistener:
        class: Pdir\ContaoKlaroConsentManager\EventListener\KlaroConfigListener
        arguments:
            - "@request_stack"
            - "@session"
            - "@logger"
