services:

    pdir.klaro.configlistener:
        class: Pdir\ContaoKlaroConsentManager\EventListener\KlaroConfigListener

    pdir.klaro.servicelistener:
        class: Pdir\ContaoKlaroConsentManager\EventListener\KlaroServiceListener

    pdir.klaro.translationlistener:
        class: Pdir\ContaoKlaroConsentManager\EventListener\KlaroTranslationListener
        arguments:
            - '@database_connection'

    pdir.klaro.contentlistener:
        class: Pdir\ContaoKlaroConsentManager\EventListener\KlaroContentListener
