services:
    _defaults:
        autowire: true
        autoconfigure: true

    Pdir\ContaoKlaroConsentManager\Controller\FrontendModule\KlaroFeModuleController:
        tags:
            - { name: container.service_subscriber }
        public: true
        # Since Symfony 5 the container has to be set manually
        calls:
            - [ setContainer, [ '@Psr\Container\ContainerInterface' ] ]

    # Hooks
    pdir.klaro.hooks.generatepage:
        class: Pdir\ContaoKlaroConsentManager\Hooks\GeneratePageHook

    pdir.klaro.hooks.getcontentelement:
        class: Pdir\ContaoKlaroConsentManager\Hooks\GetContentElementHook

    # InsertTags
    Pdir\ContaoKlaroConsentManager\EventListener\KlaroButtonInsertTagListener:
        public: true

    # Migration
    Pdir\ContaoKlaroConsentManager\Migrations\InitialMigration:
        arguments:
            - "@database_connection"
        tags:
            - { name: contao.migration, priority: 0 }
