services:

    # Contao frontend module Pdir\ContaoKlaroConsentManager\Controller\FrontendModule\KlaroFeModuleController
    # We used annotations for tagging the frontend module category, the frontend module type and the frontend module template
    Pdir\ContaoKlaroConsentManager\Controller\FrontendModule\KlaroFeModuleController:
        tags:
            - { name: container.service_subscriber }
        public: true
        # Since Symfony 5 the container has to be set manually
        calls:
            - [ setContainer, [ '@Psr\Container\ContainerInterface' ] ]
    

